### ISSUE TITLE
Assignment 1 & 2

### ISSUE THREAD

**Issue by shadowwalker** [Upward-Spiral-Science/claritycontrol#1]
1. summary.md
2. questions.md

**Comment by shadowwalker** [comment]
opportunity
- [ ] how CLARITY make the brain transparent (intro)
- [ ] what's the impact of CLARITY
- [ ] finding structure difference in brain is possible now using CLARITY

significance
- [ ] hopely create a nuro circuit within brain structures
- [ ] establish a math model and help to make some diagnose of brain issues.
- [ ] help someone with disability to express themselves

**Comment by shadowwalker** [comment]
feasibility
- [ ] we

**Comment by mlee156** [comment]
Feasibility
- [ ] Local histogram normalization is the first step
- [ ] Specific causation might not be realistic, but general trends are realistic
- [ ] Setbacks includes computational burden, however downsampling will be used

**Comment by mlee156** [comment]
Innovation
- [ ] If we accomplish our goals, pave the way for clearer understanding of neurodegenerative diseases
- [ ] Better understanding of structural differences
- [ ] See the fine details and larger picture of the brain

**Comment by sahithigd** [comment]
Innovation

**Comment by mlee156** [comment]
3 Dimensional slices possible unlike anisotropic images

We can learn from the contiguous volume that we gain the connectivity between the parts of the brains and understand them from a deeper perspective

Traumatic brain imagery: see what changed and what activities are necessary for treatment

Bring to an abstract level

What is the significance is the most important thing

**Comment by sahithigd** [comment]
*Traumatic brain injury

**Comment by sahithigd** [comment]
Doesn't require slicing. 

Track synaptic changes pre & post event (injury) .
