### ISSUE TITLE
Assignment 4

### ISSUE THREAD

**Issue by sahithigd** [Upward-Spiral-Science/claritycontrol#3]
Formal Simulated Inference 
1. Define F (i.e. your model and assumptions)
2. Formalize test
3. Describe test statistic
4. Sample data from F∈F0
5. Sample data from F∈FA
6. Plot power vs n (i.e. perspective power analysis)
7. Plot power vs n (i.e. perspective power analysis)
8. Apply to data

**Comment by mlee156** [comment]
F = 
![screen shot 2016-02-21 at 11 12 55 pm](https://cloud.githubusercontent.com/assets/14059912/13209341/bf757ce8-d8f0-11e5-8331-9db8a50a7e79.png)

**Comment by mlee156** [comment]
where 
![screen shot 2016-02-21 at 11 14 02 pm](https://cloud.githubusercontent.com/assets/14059912/13209343/da5f3814-d8f0-11e5-9ed1-7c1b3eb8f05e.png)

**Comment by mlee156** [comment]
g_{i,j} = floor((L-1))\sum\limits_{n=0}^{f_{i, j}} p_n

\begin{equation}
p_n = z/total 
\end{equation} Where $z$ is the number of pixels with intensity n and $total$ represents the total number of pixels where $n=0, 1, ..., L-1$

**Comment by mlee156** [comment]
Define F (i.e. your model and assumptions):

We can alternatively define F as

$ℳ0:pr∣∣ℳ0(r)=∏l=0L−11porl∣∣ℳ0(rl)+εpdrl∣∣ℳ0(rl)$
$ℳ1:pr∣∣ℳ1(r)=∏l=0L−11porl∣∣ℳ1(rl)+εpdrl∣∣ℳ1(rl)$

**Comment by sahithigd** [comment]
H0: a) Highest gray value (control ) != highest gray value (cocain)
    B) Highest gray value(control) != highest gray value( fear)

HA: a) Highest gray value (control) = Highest gray value (concain)
b) Highest gray value (control) = Highest gray value (fear)

**Comment by sahithigd** [comment]
Model
F(i,j) ~ Clarity image of a particular section 
a) F(I,k) = { F(I|k)*F(k) }
F(k)= {0,1} 
- 0 = Control Image
- 1 = Cocaine Image

b) F(I,k) = { F(I|k)*F(k) }
F(k)= {0,1} 
- 0 = Control Image
- 1 = Fear Image

Formalize Test
H0:     a) F(I,0)  > || = F(I,1)
b)F(I,0)  < ||=  F(I,1)
a) The maximum gray value for Cocaine stimulated brain is equal to the control brain. 
b) The maximum gray value for fear induced brain is equal the control brain. 

HA:     a) F(I,0) < || != F(I,1)
b)F(I,0) > || != F(I,1)
 a) The maximum gray value for Cocaine stimulated brain is greater than the control brain. 
b) The maximum gray value for fear induced brain is lower than the control brain. 

Test Statistic 
F(i,j) = floor((L-1)∑_"n=0" ^"F(i,j)" ▒"Pn" )
Pn = Number of pixels of intensity n / Total number of pixels 
n = 0 ...L-1 where L is typically 256. 
F(I) = mean (F(i,j))        % mean gray value in the image

Result
We can infer from the histogram plots that the maximum gray values in cocaine stimulated brain is higher than the control brain. This is conclusive with the alternative hypothesis. This also agrees with literature that indicates that the brain is more active when stimulated by cocaine, thereby lighting up more than the control brain. 
Similar conclusions can be made on the fear induced brain.
To establish these results with high confidence we would require a large dataset.
