### ISSUE TITLE
hw5

### ISSUE THREAD

**Issue by sahithigd** [Upward-Spiral-Science/claritycontrol#5]
assumptions 
[F(X,Y) | ~~ Histogram Data]
[F_{X|0}= Norm(\mu0 )]
[F_{X|1}= Norm(\mu1 )]
[F_{X|2}= Norm(\mu2 )]
[\mu0 \neq \mu1 \neq \mu2]

**Comment by mlee156** [comment]
Elements correspond to features 1-4

**Comment by sahithigd** [comment]
# Assumptions

\begin{align}
F(x,y) | ~~ Histogram~Data \
F_{x|0} & = Norm(\mu0) \
F_{x|1} & = Norm(\mu1) \
F_{x|2} & = Norm(\mu2) \
\mu0 \neq \mu1 \neq \mu2 \
\end{align}

**Comment by sahithigd** [comment]
# Step 3: Algorithm for problem solving

Classification Techniques :
1. K Nearest Neighbors(3) - Default Parameters \
2. Support Vector Machines - Linear , C= 0.5 - Default\
3. Random Forest - Max depth = 5 , N Estimators = 10, Max Features =1 - Default\
4. Linear Discriminant Analysis \
5. Quadratic Discriminant Analysis \

We ran into errors with QDA, for which reason it was ignored in the assignment.

**Comment by sahithigd** [comment]
# Step 2: Formally Define Classification / Regression problem

\begin{align}
X = {\mu0, \mu1, \mu2}\
Y = { 0, 1, 2} \
\end{align}

Classification is applied to reduce the estimated error.
The expected error is given by,
\begin{align}
E = \sum Θ ( \hat{Y}  \neq Y)\
\end{align}

**Comment by sahithigd** [comment]
add this to step 1 

Histogram Equalization 
\begin{align}
F(k) = floor((L-1) \sum_{n=0}^k p_n ) \
n = 0, 1..L-1 \
L=256 \
\end{align}
